# Generated by Django 2.2.2 on 2020-07-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_blog_app', '0002_auto_20200713_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reviews',
            field=models.PositiveIntegerField(default=0, verbose_name='评论量'),
        ),
    ]
